export const QUADRANTS = [
  {
    id: 1,
    label: 'Urgent + Important',
    subtitle: 'Do now',
    badgeBg: 'bg-green-500',
    countBg: 'bg-green-100',
    countText: 'text-green-600',
    checkColor: 'text-green-500',
    borderHover: 'hover:border-green-300',
  },
  {
    id: 2,
    label: 'Important + Not Urgent',
    subtitle: 'Schedule',
    badgeBg: 'bg-blue-500',
    countBg: 'bg-blue-100',
    countText: 'text-blue-600',
    checkColor: 'text-blue-500',
    borderHover: 'hover:border-blue-300',
  },
  {
    id: 3,
    label: 'Urgent + Not Important',
    subtitle: 'Delegate',
    badgeBg: 'bg-amber-500',
    countBg: 'bg-amber-100',
    countText: 'text-amber-700',
    checkColor: 'text-amber-500',
    borderHover: 'hover:border-amber-300',
  },
  {
    id: 4,
    label: 'Not Urgent + Not Important',
    subtitle: 'Eliminate',
    badgeBg: 'bg-red-400',
    countBg: 'bg-red-100',
    countText: 'text-red-500',
    checkColor: 'text-red-400',
    borderHover: 'hover:border-red-300',
  },
]

export const TIME_HORIZONS = [
  { id: 'daily', label: 'Daily' },
  { id: 'weekly', label: 'Weekly' },
  { id: 'monthly', label: 'Monthly' },
  { id: 'yearly', label: 'Yearly' },
]

export const INITIAL_TASKS = [
  {
    id: '1',
    title: 'Finish client proposal',
    timeHorizon: 'daily',
    quadrant: 1,
    completed: false,
    dueDate: null,
    dueTime: '10:00 AM',
  },
  {
    id: '2',
    title: 'Reply to important emails',
    timeHorizon: 'daily',
    quadrant: 1,
    completed: false,
    dueDate: null,
    dueTime: '11:30 AM',
  },
  {
    id: '3',
    title: 'Fix login issue',
    timeHorizon: 'daily',
    quadrant: 1,
    completed: false,
    dueDate: null,
    dueTime: '2:00 PM',
  },
  {
    id: '4',
    title: 'Plan marketing strategy',
    timeHorizon: 'daily',
    quadrant: 2,
    completed: false,
    dueDate: 'May 27',
    dueTime: null,
  },
  {
    id: '5',
    title: 'Exercise',
    timeHorizon: 'daily',
    quadrant: 2,
    completed: false,
    dueDate: 'May 25',
    dueTime: null,
  },
  {
    id: '6',
    title: 'Learn new skill',
    timeHorizon: 'daily',
    quadrant: 2,
    completed: false,
    dueDate: 'May 30',
    dueTime: null,
  },
  {
    id: '7',
    title: 'Schedule team meeting',
    timeHorizon: 'daily',
    quadrant: 3,
    completed: false,
    dueDate: null,
    dueTime: '3:00 PM',
  },
  {
    id: '8',
    title: 'Respond to non-urgent DMs',
    timeHorizon: 'daily',
    quadrant: 3,
    completed: false,
    dueDate: null,
    dueTime: '4:00 PM',
  },
  {
    id: '9',
    title: 'Scroll social media',
    timeHorizon: 'daily',
    quadrant: 4,
    completed: false,
    dueDate: null,
    dueTime: null,
  },
  {
    id: '10',
    title: 'Watch random videos',
    timeHorizon: 'daily',
    quadrant: 4,
    completed: false,
    dueDate: null,
    dueTime: null,
  },
]
